[theme]

# Primary accent for interactive elements
primaryColor = '#005580'

# Color used for almost all text
textColor = '#000000'

# Background color for the main content area
backgroundColor = '#f5ffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#36B9CC'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"